# Generated by Django 4.1.2 on 2022-10-10 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("tag", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("views", models.IntegerField(default=0)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/%Y/%m/%d",
                        verbose_name="",
                    ),
                ),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("photo_main", models.ImageField(upload_to="photos/%Y/%m/%d")),
                ("photo_1", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d")),
                ("photo_2", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d")),
                ("photo_3", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d")),
            ],
        ),
    ]
