# Generated by Django 4.1.2 on 2022-10-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_photo_main"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="vide_link", new_name="vide0_link",
        ),
    ]
