# Generated by Django 4.1.2 on 2022-10-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_vide_link_post_vide0_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="vide0_link", new_name="video_link",
        ),
    ]
