# Generated by Django 4.1.2 on 2022-10-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="user_id", new_name="user",
        ),
    ]
