# Generated by Django 4.1.2 on 2022-10-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("contacts", "0002_rename_user_id_contact_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
    ]
