# Generated by Django 4.1.2 on 2022-10-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name": "Story", "verbose_name_plural": "Stories"},
        ),
    ]
