# Generated by Django 4.1.2 on 2022-10-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mian_photo", models.ImageField(upload_to="setup/photos/")),
                ("instagram", models.CharField(blank=True, max_length=255)),
                ("vk", models.CharField(blank=True, max_length=255)),
                ("pinterest", models.CharField(blank=True, max_length=255)),
                ("twitter", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(max_length=500)),
                ("subtitle", models.CharField(max_length=500)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
