# Generated by Django 4.1.2 on 2022-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
