# Generated by Django 4.1.2 on 2022-10-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/%d"
            ),
        ),
    ]
