# Generated by Django 4.1.2 on 2022-10-11 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("photo_main", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                (
                    "photo_1",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "photo_2",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "photo_3",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("views", models.IntegerField(default=0)),
                ("tag_1", models.CharField(max_length=200)),
                ("tag_2", models.CharField(blank=True, max_length=200)),
                ("tag_3", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
